# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token a2e0a9b36570ff5f8ff322029f874ffb3a4042b7

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

DELETE  {{baseUrl}}/advertisements/84/
Content-Type: application/json
Authorization: Token 473dd1d24df69748e872e3eec30f5560bdf24c35

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/56/
Content-Type: application/json
Authorization: Token a2e0a9b36570ff5f8ff322029f874ffb3a4042b7

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?status=DRAFT
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2024-04-19
Content-Type: application/json

###

#получение токена для пользователя
POST http://localhost:8000/api-token-auth
Content-Type: application/json

{
  "username": "MyUser2",
  "password": "D!12345678" 
}

###

#изменение объявления админом
PATCH {{baseUrl}}/advertisements/108/
Content-Type: application/json
Authorization: Token a2e0a9b36570ff5f8ff322029f874ffb3a4042b7

{
  "status": "OPEN"
}

###

#добавление в избранное

POST {{baseUrl}}/advertisements/102/add_favourite/
Content-Type: application/json
Authorization: Token a2e0a9b36570ff5f8ff322029f874ffb3a4042b7

###

#фильтрация по избранным

GET {{baseUrl}}/advertisements/favourites
Content-Type: application/json
Authorization: Token a2e0a9b36570ff5f8ff322029f874ffb3a4042b7

###

#удаление из избранного
DELETE {{baseUrl}}/advertisements/102/del_favourite/
Content-Type: application/json
Authorization: Token a2e0a9b36570ff5f8ff322029f874ffb3a4042b7

